services:
  app:
    image: tarunsaxena111/todo-app-frontend:latest
    ports:
      - "3000:3000"
    container_name: todo-app-frontend
    depends_on:
      - http_server
      - websocket
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NEXT_PUBLIC_WS_URL: ws://localhost:3002

  http_server:
    image: tarunsaxena111/todo-app-backend:latest
    ports:
      - "3001:3001"
    container_name: todo-app-backend
    env_file:
      - .env

  websocket:
    image: tarunsaxena111/todo-app-websocket:latest
    ports:
      - "3002:3002"
    container_name: todo-app-websocket
    env_file:
      - .env
