FROM node:24-alpine

WORKDIR /app

COPY package*.json ./


COPY packages/db/package*.json ./packages/db/
COPY apps/websocket/package*.json ./apps/websocket/

RUN npm install

COPY ./apps/websocket ./apps/websocket

RUN npm run build --workspace=websocket

EXPOSE 3002

CMD ["npm", "run", "start", "--workspace=websocket"]