FROM node:24-alpine

WORKDIR /app

COPY package*.json ./


COPY packages/db/package*.json ./packages/db/
COPY apps/websocket/package*.json ./apps/websocket/

RUN npm install

COPY ./packages/db ./packages/db
COPY ./apps/websocket ./apps/websocket

RUN npx prisma generate --schema ./packages/db/prisma/schema.prisma

RUN npm run build --workspace=@repo/db
RUN npm run build --workspace=websocket

EXPOSE 3002

CMD ["sh", "-c", "npx prisma migrate deploy --schema ./packages/db/prisma/schema.prisma && npm run start --workspace=websocket"]
