FROM node:24-alpine

WORKDIR /app

COPY package*.json ./

COPY packages/db/package*.json ./packages/db/
COPY apps/web/package*.json ./apps/web/

RUN npm install

COPY ./packages/db ./packages/db
COPY ./apps/web ./apps/web

RUN npx prisma generate --schema ./packages/db/prisma/schema.prisma

# Declare build arguments
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_WS_URL

# Set environment variables for build time
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_WS_URL=$NEXT_PUBLIC_WS_URL

RUN npm run build --workspace=@repo/db
RUN npm run build --workspace=web

EXPOSE 3000

CMD ["npm", "run", "start", "--workspace=web"]
